services:
  postgres:
    image: postgres:18.0-alpine
    container_name: postgres-tasks
    hostname: ${POSTGRES_HOSTNAME}
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "port=${TASKS_POSTGRES_PORT}"
    ports:
      - "${TASKS_POSTGRES_PORT}:${TASKS_POSTGRES_PORT}"
    expose:
      - "${TASKS_POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${TASKS_POSTGRES_DATABASE}
      - PGDATA=/var/lib/postgresql/18/docker/tasks
      - TZ=${TZ}
    volumes:
      - ${TASKS_DATA_PATH}/var/lib/postgresql/18/docker/tasks
    networks:
      - pollex-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -p ${TASKS_POSTGRES_PORT}",
        ]
      interval: 2s
      timeout: 5s
      retries: 5
  api:
    image: ${DOCKER_REGISTRY}/tasks:dev
    pull_policy: never
    container_name: api-tasks
    hostname: api
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/tasks/dockerfile
    ports:
      - "${TASKS_API_PORT}:${TASKS_API_PORT}"
    environment:
      - TASKS_POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:${TASKS_POSTGRES_PORT}/${TASKS_POSTGRES_DATABASE}
      - NODE_ENV=production
      - TZ=${TZ}
    networks:
      - pollex-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  pollex-network:
    external: true
