services:
  postgres-tasks:
    image: postgres:18.0-alpine
    container_name: postgres-tasks
    hostname: postgres-tasks
    restart: unless-stopped
    ports:
      - "5431:5431"
    expose:
      - "${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}-tasks
      - PGDATA=/var/lib/postgresql/18/docker
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH}/var/lib/postgresql/18/docker
    networks:
      - pollex-internal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  api-tasks:
    image: ${DOCKER_REGISTRY}/tasks-pollex:dev
    pull_policy: never
    container_name: tasks-pollex
    hostname: tasks-pollex
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/spaces_tasks/dockerfile
    ports:
      - "7001:${API_PORT}"
    networks:
      - pollex-internal-network
    depends_on:
      postgres-tasks:
        condition: service_healthy

networks:
  pollex-internal-network:
    driver: bridge
