# pollex-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pollex-api-secrets
type: Opaque # Standard type for user-defined data
data:
  # Base64 encoded values (KEY: base64(VALUE))
  PROJECT_NAME: cG9sbGV4
  TZ: VVRD
  CONFIG_PATH: Li4vLi4vY29uZmlnOg==
  POSTGRES_HOSTNAME: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM= # Base64 encoded 'postgres'
  TASKS_POSTGRES_PORT: NTQzMQ==
  TASKS_POSTGRES_DATABASE: dGFza3M=
  TASKS_DATA_PATH: Li4vLi4vZGF0YS90YXNrcy9wb3N0Z3Jlczo=
  TASKS_POSTGRES_URL: "cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlczo1NDMxL3Rhc2tz"
  TASKS_API_PORT: NTE3Mw==
  USERS_POSTGRES_PORT: NTQzMg==
  USERS_POSTGRES_DATABASE: dXNlcnM=
  USERS_DATA_PATH: Li4vLi4vZGF0YS91c2Vycy9wb3N0Z3Jlczo=
  USERS_POSTGRES_URL: "cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlczo1NDMyL3VzZXJz"
  USERS_API_PORT: NTE3NA==
  MONGO_HOSTNAME: bW9uZ28=
  MONGO_USER: bW9uZ28=
  MONGO_PASSWORD: bW9uZ28= # Base64 encoded 'mongo'
  DOCS_MONGO_PORT: MjcwMTc=
  DOCS_MONGO_DATABASE: GRvY3VtZW50cw==
  DOCS_DATA_PATH: Li4vLi4vZGF0YS9kb2N1bWVudHMvbW9uZ29kYjo=
  MONGODB_URL: "bW9uZ29kYitsrv://mongo:mongo@cluster0.jghssvm.mongodb.net/" # Base64 encoded URL
  DOCS_API_PORT: NTE3NQ==
  SESSION_KEY: YWNxd2RlY2FyY2hyeXViYnI1N200NTUzNTIzNDEzNHY= # Base64 encoded SESSION_KEY
  JWT_PRIVATE_KEY: eW91cl9qd3RfcHJpdmF0ZV9rZXk= # Base64 encoded key
  JWT_HEADER_KEY: QXV0aG9yaXphdGlvbg==
  SSL_KEY_PATH: Li9taWRkbGV3YXJlL2NlcnRzL3NlcnZlci5rZXk=
  SSL_CERT_PATH: Li9taWRkbGV3YXJlL2NlcnRzL3NlcnZlci5jcnQ=
  DOCKER_REGISTRY: bHVpc2ZlcnJlaXJhMjM=
